import 'dart:convert';
import 'package:flutter_application_11/model/modelclass.dart';
import 'package:http/http.dart' as http;
class Apicall {
  var idUrl = 'https://run.mocky.io/v3/bdcdffd7-df4c-4645-8290-d451ea6fe98a';
  Future<List> getprofile() async {
    http.Response res = await http.get(Uri.parse(idUrl));
    try {
      if (res.statusCode == 200) {
        List pro = json.decode(res.body);

        return pro.map((e) => Autogenerated.fromJson(e)).toList();
      } else {
        return [];
      }
    } catch (e) {
      return [];
    }
  }
}
